#! /usr/bin/env php

<?php
error_reporting(E_ERROR);
ini_set('display_errors', 1);

use Spatie\Commands\ScanCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
    require __DIR__.'/vendor/autoload.php';
}
else
{
    require __DIR__.'/../../autoload.php';
}

$application = new Application('Mixed Content Scanner', '0.7');

$scanCommand = new ScanCommand();

$application->add($scanCommand);

$application->setDefaultCommand($scanCommand->getName());

$application->run();