#! /usr/bin/env php

<?php
error_reporting(E_ERROR);
ini_set('display_errors', 1);

use Spatie\Commands\ScanCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$application = new Application('Mixed Content Scanner', '0.2');

$scanCommand = new ScanCommand();

$application->add($scanCommand);

$application->setDefaultCommand($scanCommand->getName());

$application->run();